{
 "title": "Flowman",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": { "query": "job_runtime" } },
   { "name": "phase", "label": "Phase", "query": { "query": "job_runtime" } }
  ]
 },
 "panels": [
  {
   "title": "Job Runtime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "job_runtime{job=\"$job\", phase=\"$phase\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Target Records",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "target_records{job=\"$job\", phase=\"$phase\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Target Runtime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "target_runtime{job=\"$job\", phase=\"$phase\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}